using Comienzo.Models;

namespace Comienzo.Services;

internal static class SettingsCatalog
{
    public static IReadOnlyList<CatalogItem> Create() => Raw.Select(x => new CatalogItem
    {
        Name = x.Name,
        Subtitle = "Windows Settings",
        SearchTerms = x.Aliases,
        Kind = ItemKind.Setting,
        Target = x.Uri,
        IconSource = "settings"
    }).ToArray();

    private static readonly (string Name, string Uri, string Aliases)[] Raw =
    {
        ("Settings", "ms-settings:", "preferences windows"),
        ("Display", "ms-settings:display", "monitor resolution scale orientation brightness screen"),
        ("Advanced display", "ms-settings:display-advanced", "refresh rate hertz hz frequency resolution monitor gpu"),
        ("HDR", "ms-settings:display", "high dynamic range screen monitor hdr video windows hd color"),
        ("Graphics", "ms-settings:display-advancedgraphics", "gpu performance applications apps games"),
        ("Night light", "ms-settings:nightlight", "blue light filter temperature color screen night"),
        ("Sound", "ms-settings:sound", "audio volume speakers microphone input output"),
        ("Volume mixer", "ms-settings:apps-volume", "audio volume applications apps device"),
        ("Notifications", "ms-settings:notifications", "alerts do not disturb focus"),
        ("Power and battery", "ms-settings:powersleep", "sleep battery power turn off screen"),
        ("Storage", "ms-settings:storagesense", "disk space temporary files cleanup"),
        ("Installed apps", "ms-settings:appsfeatures", "programs uninstall repair applications"),
        ("Default apps", "ms-settings:defaultapps", "default programs browser extensions"),
        ("Startup apps", "ms-settings:startupapps", "boot start automatically programs"),
        ("Optional features", "ms-settings:optionalfeatures", "windows features install components"),
        ("Multitasking", "ms-settings:multitasking", "windows desktops snap alt tab"),
        ("Bluetooth and devices", "ms-settings:bluetooth", "bluetooth peripherals pair connect"),
        ("Printers and scanners", "ms-settings:printers", "printer scanner add devices"),
        ("Mouse", "ms-settings:mousetouchpad", "mouse pointer speed buttons wheel"),
        ("Touchpad", "ms-settings:devices-touchpad", "touchpad gestures laptop"),
        ("Typing", "ms-settings:typing", "typing autocorrect physical keyboard"),
        ("Cameras", "ms-settings:camera", "webcam camera devices"),
        ("USB", "ms-settings:usb", "devices usb connection errors"),
        ("Network and Internet", "ms-settings:network-status", "internet connection adapters network status"),
        ("Wi-Fi", "ms-settings:network-wifi", "wifi wireless networks connection"),
        ("Manage known networks", "ms-settings:network-wifisettings", "wifi wireless forget manage networks password"),
        ("Ethernet", "ms-settings:network-ethernet", "cable lan adapter network"),
        ("VPN", "ms-settings:network-vpn", "virtual private network tunnel connection"),
        ("Mobile hotspot", "ms-settings:network-mobilehotspot", "share internet hotspot wifi"),
        ("Proxy", "ms-settings:network-proxy", "proxy server internet network"),
        ("Data usage", "ms-settings:datausage", "consumption traffic network internet"),
        ("Advanced network settings", "ms-settings:network-advancedsettings", "adapters ip dns network reset"),
        ("Personalization", "ms-settings:personalization", "appearance theme background colors"),
        ("Background", "ms-settings:personalization-background", "wallpaper desktop image"),
        ("Colors", "ms-settings:colors", "dark light theme accent color transparency"),
        ("Themes", "ms-settings:themes", "appearance sounds cursor desktop"),
        ("Lock screen", "ms-settings:lockscreen", "lock background screen saver"),
        ("Taskbar", "ms-settings:taskbar", "start icons system tray taskbar"),
        ("Fonts", "ms-settings:fonts", "typefaces letters install"),
        ("Accounts", "ms-settings:accounts", "user microsoft account information"),
        ("Sign-in options", "ms-settings:signinoptions", "password pin windows hello fingerprint security change password"),
        ("Other users", "ms-settings:otherusers", "family users accounts add"),
        ("Windows backup", "ms-settings:backup", "backup sync onedrive preferences"),
        ("Date and time", "ms-settings:dateandtime", "clock time zone date"),
        ("Language and region", "ms-settings:regionlanguage", "language country region format keyboard"),
        ("Privacy and security", "ms-settings:privacy", "permissions data privacy security"),
        ("Windows Security", "windowsdefender:", "defender antivirus firewall protection threats"),
        ("Location", "ms-settings:privacy-location", "gps location permissions"),
        ("Camera permissions", "ms-settings:privacy-webcam", "privacy camera applications permissions"),
        ("Microphone permissions", "ms-settings:privacy-microphone", "privacy microphone audio permissions"),
        ("Windows Update", "ms-settings:windowsupdate", "updates check install"),
        ("Update history", "ms-settings:windowsupdate-history", "installed updates uninstall update"),
        ("Advanced Windows Update options", "ms-settings:windowsupdate-options", "updates restart schedule"),
        ("Recovery", "ms-settings:recovery", "reset pc advanced startup reinstall"),
        ("Activation", "ms-settings:activation", "license product key windows"),
        ("Troubleshoot", "ms-settings:troubleshoot", "errors diagnostics repair"),
        ("About", "ms-settings:about", "system information pc ram processor computer name windows version"),
        ("Remote Desktop", "ms-settings:remotedesktop", "rdp remote access computer"),
        ("Clipboard", "ms-settings:clipboard", "copy paste history sync"),
        ("Developer mode", "ms-settings:developers", "development sideload terminal powershell"),
        ("Accessibility", "ms-settings:easeofaccess", "accessibility disability vision hearing"),
        ("Text size", "ms-settings:easeofaccess-display", "letters large text accessibility"),
        ("Narrator", "ms-settings:easeofaccess-narrator", "screen reader accessibility voice"),
        ("Magnifier", "ms-settings:easeofaccess-magnifier", "magnify zoom screen accessibility"),
        ("Contrast themes", "ms-settings:easeofaccess-highcontrast", "high contrast themes accessibility"),
        ("Gaming", "ms-settings:gaming-gamebar", "game bar xbox captures"),
        ("Game Mode", "ms-settings:gaming-gamemode", "performance games gaming"),
    };
}
