using Comienzo.Models;

namespace Comienzo.Services;

internal static class SettingsCatalog
{
    public static IReadOnlyList<CatalogItem> Create() => Raw.Select(x => new CatalogItem
    {
        Name = x.Name,
        Subtitle = "Configuración de Windows",
        SearchTerms = x.Aliases,
        Kind = ItemKind.Setting,
        Target = x.Uri,
        IconSource = "settings"
    }).ToArray();

    private static readonly (string Name, string Uri, string Aliases)[] Raw =
    {
        ("Configuración", "ms-settings:", "ajustes preferencias windows"),
        ("Pantalla", "ms-settings:display", "monitor resolución escala orientación brillo pantalla"),
        ("Pantalla avanzada", "ms-settings:display-advanced", "hercios hz frecuencia resolución monitor gpu"),
        ("HDR", "ms-settings:display", "alto rango dinámico pantalla monitor hdr vídeo windows hd color"),
        ("Gráficos", "ms-settings:display-advancedgraphics", "gpu rendimiento aplicaciones juegos"),
        ("Luz nocturna", "ms-settings:nightlight", "filtro azul temperatura color pantalla noche"),
        ("Sonido", "ms-settings:sound", "audio volumen altavoces micrófono entrada salida"),
        ("Mezclador de volumen", "ms-settings:apps-volume", "audio volumen aplicaciones dispositivo"),
        ("Notificaciones", "ms-settings:notifications", "avisos no molestar concentración"),
        ("Energía y batería", "ms-settings:powersleep", "suspensión batería energía apagar pantalla"),
        ("Almacenamiento", "ms-settings:storagesense", "disco espacio archivos temporales limpieza"),
        ("Aplicaciones instaladas", "ms-settings:appsfeatures", "programas desinstalar reparar aplicaciones"),
        ("Aplicaciones predeterminadas", "ms-settings:defaultapps", "programas por defecto navegador extensiones"),
        ("Aplicaciones de inicio", "ms-settings:startupapps", "arranque iniciar automáticamente programas"),
        ("Características opcionales", "ms-settings:optionalfeatures", "funciones windows instalar componentes"),
        ("Multitarea", "ms-settings:multitasking", "ventanas escritorios ajustar snap alt tab"),
        ("Bluetooth y dispositivos", "ms-settings:bluetooth", "bluetooth periféricos emparejar conectar"),
        ("Impresoras y escáneres", "ms-settings:printers", "impresora escáner añadir dispositivos"),
        ("Ratón", "ms-settings:mousetouchpad", "mouse puntero velocidad botones rueda"),
        ("Panel táctil", "ms-settings:devices-touchpad", "touchpad gestos portátil"),
        ("Teclado", "ms-settings:typing", "escritura autocorrección teclado físico"),
        ("Cámaras", "ms-settings:camera", "webcam cámara dispositivos"),
        ("USB", "ms-settings:usb", "dispositivos usb conexión errores"),
        ("Red e Internet", "ms-settings:network-status", "internet conexión adaptadores red estado"),
        ("Wi-Fi", "ms-settings:network-wifi", "wifi inalámbrica redes conexión"),
        ("Redes Wi-Fi conocidas", "ms-settings:network-wifisettings", "wifi inalámbrica olvidar administrar redes contraseña"),
        ("Ethernet", "ms-settings:network-ethernet", "cable lan adaptador red"),
        ("VPN", "ms-settings:network-vpn", "red privada túnel conexión"),
        ("Punto de acceso móvil", "ms-settings:network-mobilehotspot", "compartir internet hotspot wifi"),
        ("Proxy", "ms-settings:network-proxy", "servidor proxy internet red"),
        ("Uso de datos", "ms-settings:datausage", "consumo tráfico red internet"),
        ("Configuración de red avanzada", "ms-settings:network-advancedsettings", "adaptadores ip dns restablecer red"),
        ("Personalización", "ms-settings:personalization", "apariencia tema fondo colores"),
        ("Fondo", "ms-settings:personalization-background", "wallpaper escritorio imagen"),
        ("Colores", "ms-settings:colors", "tema oscuro claro color énfasis transparencia"),
        ("Temas", "ms-settings:themes", "apariencia sonidos cursor escritorio"),
        ("Pantalla de bloqueo", "ms-settings:lockscreen", "bloqueo fondo protector pantalla"),
        ("Barra de tareas", "ms-settings:taskbar", "inicio iconos bandeja sistema taskbar"),
        ("Fuentes", "ms-settings:fonts", "tipografías letras instalar"),
        ("Cuentas", "ms-settings:accounts", "usuario cuenta microsoft información"),
        ("Opciones de inicio de sesión", "ms-settings:signinoptions", "contraseña pin windows hello huella seguridad cambiar contraseña"),
        ("Otros usuarios", "ms-settings:otherusers", "familia usuarios cuentas añadir"),
        ("Copia de seguridad de Windows", "ms-settings:backup", "backup sincronizar onedrive preferencias"),
        ("Hora y fecha", "ms-settings:dateandtime", "reloj zona horaria fecha"),
        ("Idioma y región", "ms-settings:regionlanguage", "idioma país región formato teclado"),
        ("Privacidad y seguridad", "ms-settings:privacy", "permisos datos privacidad seguridad"),
        ("Seguridad de Windows", "windowsdefender:", "defender antivirus firewall protección amenazas"),
        ("Ubicación", "ms-settings:privacy-location", "gps localización permisos"),
        ("Cámara: permisos", "ms-settings:privacy-webcam", "privacidad cámara aplicaciones permisos"),
        ("Micrófono: permisos", "ms-settings:privacy-microphone", "privacidad micro audio permisos"),
        ("Windows Update", "ms-settings:windowsupdate", "actualizaciones updates buscar instalar"),
        ("Historial de actualizaciones", "ms-settings:windowsupdate-history", "updates instaladas desinstalar actualización"),
        ("Opciones avanzadas de Windows Update", "ms-settings:windowsupdate-options", "actualizaciones reinicio horario"),
        ("Recuperación", "ms-settings:recovery", "restablecer pc inicio avanzado reinstalar"),
        ("Activación", "ms-settings:activation", "licencia clave producto windows"),
        ("Solucionar problemas", "ms-settings:troubleshoot", "errores diagnóstico reparación"),
        ("Acerca del sistema", "ms-settings:about", "información pc ram procesador nombre equipo versión windows"),
        ("Escritorio remoto", "ms-settings:remotedesktop", "rdp acceso remoto equipo"),
        ("Portapapeles", "ms-settings:clipboard", "copiar pegar historial sincronizar"),
        ("Modo desarrollador", "ms-settings:developers", "desarrollo sideload terminal powershell"),
        ("Accesibilidad", "ms-settings:easeofaccess", "accesibilidad discapacidad visión audición"),
        ("Tamaño del texto", "ms-settings:easeofaccess-display", "letras texto grande accesibilidad"),
        ("Narrador", "ms-settings:easeofaccess-narrator", "lector pantalla accesibilidad voz"),
        ("Lupa", "ms-settings:easeofaccess-magnifier", "ampliar zoom pantalla accesibilidad"),
        ("Contraste", "ms-settings:easeofaccess-highcontrast", "alto contraste temas accesibilidad"),
        ("Juegos", "ms-settings:gaming-gamebar", "game bar xbox capturas"),
        ("Modo Juego", "ms-settings:gaming-gamemode", "rendimiento juegos gaming"),
    };
}
